Fix: Pick email from order object if exists
rafflebox-technologies-inc/rafflebox-logger pull request #14
Opened 2021-12-15 18:03 UTC by akshu10

Pick Email from order and prevent overwrite from EventMember object

2021-12-15 18:12 UTC, jamie3 requested changes

2021-12-15 18:12 UTC, jamie3 commented on src/extract-fields.ts
> +      if (this.parent?.key === 'order' && this.key === 'email') {
This wont work for all the logs because some are not on the `order` node.

2021-12-15 18:17 UTC, akshu10 commented on src/extract-fields.ts
> +      if (this.parent?.key === 'order' && this.key === 'email') {
@jamie3 Thinking we should pass some identifier to the logger, that will tell the logger where the log is coming from. Thoughts?

2021-12-16 15:12 UTC, jamie3 approved these changes

2021-12-16 15:13 UTC, merged